INSERT INTO facts (fact, tidbit, verb, RE, protected, mood, chance) VALUES
('band name reply', '"$band" would be a good name for a band.', '<reply>', False, True, NULL, NULL),
('band name reply', '"$band" would be a nice name for a band.', '<reply>', False, True, NULL, NULL),
('band name reply', '"$band" would be a nice name for a rock band.', '<reply>', False, True, NULL, NULL),
('band name reply', '"$band" would make a good name for a band.', '<reply>', False, True, NULL, NULL),
('band name reply', '"$band" would make a good name for a rock band.', '<reply>', False, True, NULL, NULL),
('band name reply', 'That would be a good name for a band.', '<reply>', False, True, NULL, NULL),
('tumblr name reply', 'http://$band.tumblr.com/', '<reply>', False, True, NULL, NULL),
('don''t know', 'A thousand apologies, effendi, but I do not understand.', '<reply>', False, True, NULL, NULL),
('don''t know', 'Beeeeeeeeeeeeep!', '<reply>', False, True, NULL, NULL),
('don''t know', 'Can''t talk, zombies!', '<reply>', False, True, NULL, NULL),
('don''t know', 'Error 42: Factoid not in database.  Please contact administrator of current universe.', '<reply>', False, True, NULL, NULL),
('don''t know', 'Error at 0x08: Reference not found', '<reply>', False, True, NULL, NULL),
('don''t know', 'I cannot access that data.', '<reply>', False, True, NULL, NULL),
('don''t know', 'I do not know.', '<reply>', False, True, NULL, NULL),
('don''t know', 'I don''t know', '<reply>', False, True, NULL, NULL),
('don''t know', 'I don''t know anything about that.', '<reply>', False, True, NULL, NULL),
('don''t know', 'I''m sorry, there''s currently nothing associated with that keyphrase.', '<reply>', False, True, NULL, NULL),
('don''t know', 'Not a bloody clue, sir.', '<reply>', False, True, NULL, NULL),
('don''t know', 'UNCAUGHT EXCEPTION: TERMINATING', '<reply>', False, True, NULL, NULL),
('drops item', 'fumbles and drops $giveitem.', '<action>', False, False, NULL, NULL),
('duplicate item', '$who: I already have $item.', '<reply>', False, True, NULL, NULL),
('duplicate item', 'But I''ve already got $item!', '<reply>', False, True, NULL, NULL),
('duplicate item', 'I already have $item.', '<reply>', False, True, NULL, NULL),
('duplicate item', 'No thanks, $who, I''ve already got one.', '<reply>', False, True, NULL, NULL),
('list items', 'contains $inventory.', '<action>', False, False, NULL, NULL),
('list items', 'I am carrying $inventory.', '<reply>', False, False, NULL, NULL),
('list items', 'is carrying $inventory.', '<action>', False, False, NULL, NULL),
('pickup full', 'drops $giveitem and takes $item.', '<action>', False, True, NULL, NULL),
('pickup full', 'hands $who $giveitem in exchange for $item', '<action>', False, True, NULL, NULL),
('pickup full', 'is now carrying $item, but dropped $giveitem.', '<action>', False, True, NULL, NULL),
('takes item', 'is now carrying $item.', '<action>', False, True, NULL, NULL),
('takes item', 'now contains $item.', '<action>', False, True, NULL, NULL),
('takes item', 'Okay, $who.', '<reply>', False, True, NULL, NULL);